name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
    node-version:
       description: 'NodeJS version to use'
       default: '20.x'
    working-dir:
      description: 'The working directory of the application'
      default: './'
    target-env:
      description: '"dev" or "prod". Controls whether dev dependencies are installed'
      default: 'dev'
      required: false
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS version ${{inputs.node-version}}
      shell: bash
      run: npm init --yes --version ${{inputs.node-version}}
      
    
    - name: Cache dependencies
      id: cache
      shell: bash
      working-directory: ${{inputs.working-dir}}
      run: |
        if [ -f "package-lock.json" ]; then
          echo "package-lock.json encontrado en ${{inputs.working-dir}}"
          echo "Almacenando en caché package-lock.json..."
          CACHE_KEY="${{inputs.target-env}}-node-modules-${{ hashFiles('my-app/package-lock.json')}}"
          CACHE_PATH="/node_modules"
          echo "::set-output name=cache-hit::true"
        else
            echo "No se encontró package-lock.json en ${{inputs.working-dir}}"
            echo "::set-output name=cache-hit::false"
        fi
      
    - name: Install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{inputs.working-dir}}
      run: npm ci --omit=${{inputs.target-env}}