name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
    node-version:
       description: 'NodeJS version to use'
       default: '20.x'
    working-dir:
      description: 'The working directory of the application'
      default: './'
    target-env:
      description: '"dev" or "prod". Controls whether dev dependencies are installed'
      default: 'dev'
      required: false
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS version $INPUT_NODE_VERSION
      shell: bash
      run: npm init --yes --version $INPUT_NODE_VERSION
      
    
    - name: Cache dependencies
      id: cache
      shell: bash
      working-directory: $INPUT_WORKING_DIR
      run: |
        if [ -f "/package-lock.json" ]; then
          echo "package-lock.json encontrado en $DIRECTORY"
          echo "Almacenando en caché package-lock.json..."
          CACHE_KEY="$INPUT_TARGET_ENV-node-modules-${{ hashFiles('my-app/package-lock.json') }}"
          CACHE_PATH="/node_modules"
          echo "::set-output name=cache-hit::true"
        else
            echo "No se encontró package-lock.json en $DIRECTORY"
            echo "::set-output name=cache-hit::false"
        fi
      
    - name: Install dependencies
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: $INPUT_WORKING_DIR
      run: npm ci --omit=$INPUT_TARGET_ENV