name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
    node-version:
       description: 'NodeJS version to use'
       default: '20.x'
    working-dir:
      description: 'The working directory of the application'
      default: './'
    target-env:
      description: '"dev" or "prod". Controls whether dev dependencies are installed'
      default: 'dev'
      required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.node-version}}

    - uses: actions/cache@v3
      id: Cache
      with:
        path: ${{inputs.working-dir}}/node_modules
        key: ${{inputs.target-env}}-node-${{ hashFiles('my-app/package-lock.json') }}
        restore-keys: |
          ${{inputs.target-env}}-node-

    - name: install dep
      shell: bash
      if: steps.Cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: ${{inputs.working-dir}}

    - shell: bash
      run: npm run build
      working-directory: ${{inputs.working-dir}}

    - name: upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: myApp
        path: ${{inputs.working-dir}}/build
        
