name: 02 - Eventos
on: 
    push:
    schedule:
        - cron: '1 * * * *'
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: showTrigger
              run: | 
               echo "Event name: ${{ github.event_name }}"
    