name: 03 - Runners de workflow
on: push
jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Mostrar SO
              run: echo "Este trabajo se ejecuta en un Runner de Ubuntu"
    windows-echo:
        runs-on: windows-latest
        steps:
            - name: Mostrar SO
              run: echo "Este trabajo se ejecuta en un Runner de Windows"
    mac-echo:
        runs-on: macos-latest
        steps:
            - name: Mostrar SO
              run: | 
               echo "Este trabajo se ejecuta en un Runner MacOS"
               echo "${{runner.os}}"           
