name: 16 - Working with Matrices
on:
    workflow_dispatch: 

jobs:
    backwards-compatibility:
        runs-on: ubuntu-latest
        name: ${{matrix.os}}-${{matrix.node}}
        strategy:
            matrix:
                node: ['18.x', '20.x' , '21.x']
                os: 
                    - ubuntu-latest
                    - windows-latest
        steps:
            - name: Setup node
              uses: action/setup-node@v4
              with:
                node-version: ${{matrix.node}}

            - name: Perform some tests
              run: "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node}}"
