name: 16 - Working with Matrices
on:
    workflow_dispatch: 

jobs:
    backwards-compatibility:
        runs-on: ubuntu-latest
        name: ${{matrix.os}}-${{matrix.node}}
        strategy:
            fail-fast: false
            matrix:
                node: ['18.x', '20.x' , '21.x']
                os: 
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      node: '16.x'
                    - os: windows-latest
                      node: '20.x'
                      tag: experimental
                exclude:
                    - os: ubuntu-latest
                      node: '20.x'
        steps:
            - name: Setup node
              run: echo "set up node ${{matrix.node}}"
              
            - name: fail if experimental
              if: matrix.tag == 'experimental'
              run: exit 1

            - name: Perform some tests
              run: |
               echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node}}"
               sleep 10
               exit 0

    include-example:
        runs-on: ubuntu-latest
        name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}
        strategy:
          matrix:
            color: [red, green]
            shape: [circle, square]
            size: [small, large]
            include:
              - color: red
                shape: triangle
              - opacity: 50
              - color: red
                opacity: 75
              - shape: circle
                opacity: 100

        steps:
          - name: Dummy step
            run: |
               echo "color: ${{matrix.color}}"
               echo "shape: ${{matrix.shape}}"
               echo "size: ${{matrix.size}}"
               echo "opacity: ${{matrix.opacity}}"