name: Using Reusable WorkFlow
on:
    workflow_dispatch: 
        inputs:
            working-dir:
                type: string
                required: true
jobs:
    recall:
        uses: ./.github/workflows/15-Artifacts.yml
        with:
            working-dir: ${{inputs.working-dir}}
        